name: stores_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  args: ^2.3.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  dotenv: ^3.0.0
  mysql1: ^0.20.0
  get_it: ^7.2.0
  logger: ^1.1.0
  injectable: ^2.1.0
  jaguar_jwt: ^3.0.0

dev_dependencies:
  # http: ^0.13.5
  lints: ^2.0.0
  test: ^1.16.0
  test_process: ^2.0.3
  build_runner: 
  injectable_generator: ^2.1.3
  shelf_router_generator: ^1.0.5
